server:
  port: 8080

spring:
  application:
    name: "TalentPool"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null

  datasource:
    url: jdbc:postgresql://personas-db.c3a8sc0oeavk.us-east-2.rds.amazonaws.com:5432/personasdb
    username: postgres
    password: Aa5592770*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
